[package]
name = "crowdfunding_dao"
version = "0.1.0"
description = "Crowdfunding dao Program"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.28.0", features = ["init-if-needed"] }
anchor-spl = "0.28.0"