[package]
name = "music_nft"
version = "0.1.0"
description = "Music NFT Program"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.28.0", features = ["init-if-needed"] }
anchor-spl = "0.28.0"